const sinopse = document.getElementById("sinopse");
sinopse.addEventListener("click", () =>{
        const texto = document.getElementById("texto");
        const titulo = document.getElementById("titulo");
        texto.innerHTML = '<p>Mil anos antes do início do jogo, houvera a guerra dos Magi (War Magi), na qual três deusas tornaram os humanos seres mágicos chamados Espers (criaturas como fadas, sátiros e unicórnios). Vendo o dano que faziam, as deusas libertaram os Espers e se tranformaram em estátuas. Ao fim da guerra, vendo as grandes diferenças, os Espers se fecham em um mundo próprio, isolando-se completamente do mundo dos homens. Com isso, a magia é abolida do mundo e a humanidade se vê com a necessidade de voltar seus olhos para a tecnologia novamente.</p><p>O planeta se reconstruiu, o homem redescobriu a pólvora e as máquinas a vapor. No tempo presente, o Império, uma potência maligna e emergente liderado pelo Imperador Gestahl e seus generais - Kefka Pallazzo, Celes Chere e Leo Cristophe - está tentando ressuscitar a magia, extraíndo o poder dos Espers. Numa tentativa de invadir o mundo selado dos Espers, Gestahl encontra Terra, uma garota filha de uma humana e de um Esper chamado Maduin, com a capacidade de usar a magia. Ele a cria no seio do Império e a escraviza para lutar em sua legião.</p><p>Numa missão, ela consegue escapar do domínio que lhe era exercido com a ajuda do "caçador de tesouros", Locke, e se une aos rebeldes Returners. Ao longo de suas lutas, os Returners testemunham inúmeras atrocidades cometidas por Kefka, general do Império, e conseguem aliados entre as vítimas de seus crimes (entre eles a ex-general Celes).</p><p>Após atacarem Espers na cidade de Thamasa, o mundo dos Espers passa a flutuar - e no Continente Flutuante, Kefka trai Gestahl, e usa o poder das três estátuas das deusas da magia para reconstruir o mundo à sua imagem, conseguindo poderes divinos e isolando os heróis.</p><p>Um ano após tal incidente, o mundo perdeu as esperanças - Celes acorda numa ilha isolada, e passa a procurar os Returners sobreviventes, que partem para atacar o vilão em sua gigantesca torre.</p><p>Fonte: <a href="https://pt.wikipedia.org/wiki/Final_Fantasy_VI">Página da wikipedia do jogo</a></p>';
        titulo.innerHTML = '<h3>Sinopse</h3>';
    });

const gameplay = document.getElementById("gameplay");
gameplay.addEventListener("click", () =>{
        const texto = document.getElementById("texto");
        const titulo = document.getElementById("titulo");
        texto.innerHTML = '<p>Como os outros da série, Final Fantasy VI é dividido em 4 cenários: mapa, cidades, calabouços e batalhas. No mapa, se guiam os personagens até os locais dos eventos. Há 4 maneiras de viajar: a pé (única forma de encontrar monstros para batalhar), chocobo, navio e aeronave (conhecido como airship na série).</p><p>Em cidades normais, há uma pousada (Inn), na qual se dorme e pode-se recuperar os danos de batalha; lojas de equipamentos, onde vendem equipamentos de defesa (escudos, capacetes e armaduras), de armas (diversas, como espada, lança e garra) e acessórios (relíquias com variados efeitos para as habilidades dos personagens), e uma drogaria, com poções, tinturas e curativos em geral. Em todas as cidades há pessoas que passam informações e rumores.</p><p>Dungeons podem ser esgotos, cavernas, florestas ou construções habitados por monstros e baús com itens geralmente não achados em lojas. Algumas dungeons exigem divisão em 2 ou 3 grupos para resolver quebra-cabeças.</p><p>Em batalha há um sistema de menus, com as opções Fight (ataque), Item, Magic (usar magia) e uma habilidade única.</p><p>As batalhas rodam num sistema pseudo-tempo real chamado Active Time Battle, no qual todos os envolvidos esperam um tempo para atacar (o jogador tem barrinhas demonstrando o tempo). Após as batalhas, os personagens ganham experiência (que eleva o nível), dinheiro e, às vezes, itens.</p><p>Há uma diferença para outros jogos do gênero: pode-se escolher um personagem para aparecer na tela de mapa/cidade entre todos os do grupo corrente; em outros jogos, o personagem que aparece não pode ser alterado ou todos os personagens aparecem caminhando em fila indiana.</p><p>Os grupos têm 4 personagens, que podem ser substituídos em uma cidade em certo ponto, e na aeronave na maior parte do tempo. Os personagens, ao atacar com baixa saúde, podem desferir Limit Break (desperation attacks), técnicas únicas e poderosas ao invés de um ataque normal.</p><p>Só dois personagens usam magias no começo do jogo, mas a maior parte deles pode aprender utilizando-se de Magicite, restos mortais de Espers. Magicite é usado também para a conjurar monstros. Os personagens podem se equipar com armas, escudos, capacetes, armaduras e relíquias.</p><p>O jogo geralmente dura de 35-45 horas, embora grande parte deste tempo consista de aventuras opcionais.</p><p>Fonte: <a href="https://pt.wikipedia.org/wiki/Final_Fantasy_VI">Página da wikipedia do jogo</a></p>';
        titulo.innerHTML = '<h3>Gameplay</h3>';
    });

const imagens = document.getElementById("imagens");
imagens.addEventListener("click", () =>{
        const texto = document.getElementById("texto");
        const titulo = document.getElementById("titulo");
        texto.innerHTML = '<img src="imagens/ff6-1.png" class = "jogo" alt="foto de gameplay do jogo"><img src="imagens/ff6-2.png" class = "jogo" alt="foto de gameplay do jogo"><img src="imagens/ff6-3.png" class = "jogo" alt="foto de gameplay do jogo"><img src="imagens/ff6-4.png" class = "jogo" alt="foto de gameplay do jogo"><img src="imagens/ff6-5.png" class = "jogo" alt="foto de gameplay do jogo"><img src="imagens/ff6-6.png" class = "jogo" alt="foto de gameplay do jogo">';
        titulo.innerText = "Imagens do Jogo";
    });
